name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
  
    - name: Install requirements
      run: |
        pip install pipx
        pipx install cookiecutter
        pipx runpip cookiecutter install -r requirements.txt

    - name: Linting code by flake8
      run: |
        pipx run flake8 --show-source --statistics
        
    - name: Check types by pyright
      run: |
        pipx run pyright
